Parasites Web Application/cs36-main-master/parasites/urls.py
"""parasites URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from parasites_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('parasites_app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Parasites Web Application/cs36-main-master/parasites_app/urls.py
from django.urls import path
from django.contrib import admin
from parasites_app import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "parasites_app"

urlpatterns = [
    #login pages
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('admin/', admin.site.urls),
    #public content
    #the two following are repeaated
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('public_post/<str:pk>/', views.public_post, name='public_post'),
    
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('parasites/', views.parasites, name='parasites'),
    path('parasites/<slug:parasite_name_slug>/',views.view_parasite, name='view_parasite'),
    
    #user pages
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/', views.profile, name='profile'),
    
    #researcher pages
    path('researcher/', views.researcher, name='researcher'),
    path('researcher_post/<str:pk>/', views.researcher_post, name='researcher_post'),
    path('add_researcher_post/', views.add_researcher_post, name='add_researcher_post'),

    
    #clinician pages
    path('clinician/', views.clinician, name='clinician'),
    path('clinician_post/<str:pk>/', views.clinician_post, name='clinician_post'),
    path('add_clinician_post/', views.add_clinician_post, name='add_clinician_post'),

  
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Parasites Web Application/cs36-main-master/parasites_app/models.py
#parasites_app
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from PIL import Image
from ckeditor.fields import RichTextField
    
ROLES = (
    ('0','Researcher'),
    ('1','Clinician'),
    )

POST_TYPE = (
    ('0','Researcher'),
    ('1','Clinician'),
    ('2', 'Public'),
    )

FILE_TYPE = (
    ('0','Video'),
    ('1','Photo'),
    ('2','PDF'),
    ('3','Other'),
    )

class UserProfile(AbstractUser):
    picture = models.ImageField(upload_to='profile_images/', default='profile_images/default.png')
    role = models.CharField(max_length=1000, choices=ROLES, default='0')
    
    def __str__(self):
        return self.email
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        #Locate image
        #resize for fluidity
        try:
            pic = Image.open(self.picture.path)
            if pic.width > 240 or pic.width  > 240:
                processed = (240, 240)
                pic.thumbnail(processed) #Resize
            pic.save(self.picture.path) # Override current picture with resized one
        except:
            pass

class Parasite(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to='parasite_images', blank=True)
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Parasite, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.name
        
class AboutUs(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to='aboutus_images', blank=True)
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(AboutUs, self).save(*args, **kwargs)
        
    class Meta:
        verbose_name_plural = 'About Us'
        
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.TextField(max_length=50)
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    parasite = models.ForeignKey(Parasite, default='None', on_delete=models.CASCADE)
    post_type = models.CharField(max_length=1000, choices=POST_TYPE, default='0')
    
    def __str__(self):
        return self.title + ': ' + str(self.pk)
    
    def get_absolute_url(self):
        return reverse('post', kwargs={'pk': self.pk})


    
class Comment(models.Model):
    user = models.ForeignKey(UserProfile, related_name="profile", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="post", on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email + ': ' +   self.text
    
class File(models.Model):
    file = models.FileField(upload_to='user/%Y/%m/%d/', blank=True, null=True)
    file_type = models.CharField(max_length=1000, choices=FILE_TYPE, default='3')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    number = models.IntegerField()
    
    def __str__(self):
        return self.post.title + ': ' + str(self.number)

Parasites Web Application/cs36-main-master/parasites_app/forms.py
from django import forms
from parasites_app.models import UserProfile, Comment, Post, File
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import PasswordChangeForm

class PasswordChangeCustomForm(PasswordChangeForm):
    def __init__(self, user, *args, **kwargs):
        super(PasswordChangeCustomForm, self).__init__(user,*args, **kwargs)
        for field in self.fields:
            self.fields['old_password'].widget.attrs.update({'class': 'form-control'})
            self.fields['new_password1'].widget.attrs.update({'class': 'form-control'})
            self.fields['new_password2'].widget.attrs.update({'class': 'form-control'})
            
class ContactForm(forms.Form):
    first_name = forms.CharField(max_length = 50)
    last_name = forms.CharField(max_length = 50)
    email_address = forms.EmailField(max_length = 150)
    message = forms.CharField(widget = forms.Textarea, max_length = 2000)


class EditProfileForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('email',
                   'username'
                 )

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)
            

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text','parasite')
            
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

        widgets = {
            'text': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Post a comment...'}),
}
class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file', 'file_type')

Parasites Web Application/cs36-main-master/parasites_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from parasites_app.models import *
from parasites_app.forms import ContactForm, EditProfileForm, UserProfileForm, PostForm, CommentForm, FileForm, PasswordChangeCustomForm
from django.core.mail import send_mail
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError

#create decorators to dictate permissions
#@clinician_required
def clinician_required(function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url='login'):
    actual_decorator = user_passes_test(
        lambda u: (u.is_superuser or u.role == '1'),
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    if function:
        return actual_decorator(function)
    return actual_decorator

#login pages
def user_login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('home'), context)
            else:
                return HttpResponse("Your account does not exist.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'parasites_app/user_login.html', context)


@login_required(login_url='/login/')
def user_logout(request):
    logout(request)
    return redirect(reverse('home')) 

#public content
def home(request):
    context = {}
    parasite = request.GET.get('parasite')
    posts = Post.objects.filter(post_type='2').order_by('-date_posted')
    if parasite != None:
        posts = posts.filter(
            parasite__name=parasite)
    parasites = Parasite.objects.all()
    context['parasites'] = parasites
    context['posts'] = posts
    return render(request,'parasites_app/home.html', context) 

def public_post(request, pk):
    post = Post.objects.filter(pk = pk)[0]
    context_dict={}
    context_dict['post'] = post
    context_dict['profile'] = post.user
    context_dict['files'] = File.objects.filter(post=post)
    return render(request,'parasites_app/public_post.html',context = context_dict)
    
def parasites(request):
    context = {}
    c = Parasite.objects.all().order_by('name')
    context['c'] = c 
    return render(request, 'parasites_app/parasites.html',context)

def about(request):
    context = {}
    c = AboutUs.objects.all()
    context['c'] = c 
    return render(request, 'parasites_app/about.html',context)

def contact(request):
    if request.method == 'POST':
	    form = ContactForm(request.POST)
	    if form.is_valid():
		    subject = "Website Inquiry" 
		    body = {
		    'first_name': form.cleaned_data['first_name'], 
			'last_name': form.cleaned_data['last_name'], 
			'email': form.cleaned_data['email_address'], 
			'message':form.cleaned_data['message'], 
			}
		    message = "\n".join(body.values())

		    try:
			    send_mail(subject, message, 'parasitescontactus@gmail.com', ['parasitescontactus@gmail.com']) 
		    except BadHeaderError:
			    return HttpResponse('Invalid header found.')
      
    form = ContactForm()
    return render(request, "parasites_app/contact.html", {'form':form})

def view_parasite(request,parasite_name_slug):
    context_dict = {}
    try:
        parasite = Parasite.objects.get(slug=parasite_name_slug)
        context_dict['parasite'] = parasite
    except Parasite.DoesNotExist:
       context_dict['parasite'] = None
    return render(request, 'parasites_app/viewpara.html', context = context_dict)

@login_required(login_url='/login/')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeCustomForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)  # Important!
            messages.success(request, 'Your password was successfully updated!',extra_tags='alert-success')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeCustomForm(request.user)
    return render(request, 'parasites_app/change_password.html', {
        'form': form
    })

#user pages
@login_required(login_url='/login/')
def edit_profile(request):
    if request.method == 'POST':
        f = EditProfileForm(request.POST, instance=request.user)
        pf = UserProfileForm(request.POST, request.FILES, instance=request.user)
        if f.is_valid() and pf.is_valid():
            #Save user data to database
            f.save()
            pf.save()
            messages.success(request, 'Your profile was successfully edited')
            return redirect(reverse('profile'))
    else:
        form = EditProfileForm(instance=request.user)
        pf = UserProfileForm(instance=request.user)
        context = {}
        context['form'] = form
        context['profile_form'] = pf
        
        
        return render(request, 'parasites_app/edit_profile.html', context)

@login_required(login_url='/login/')
def profile(request):
    context_dict = {}
    try:
        profile = request.user
        #print(profile.query)
        context_dict['profile'] = profile
    except UserProfile.DoesNotExist:
        context_dict['profile'] = None
        print("failed")
    print(context_dict)
    return render(request, 'parasites_app/profile.html', context=context_dict)
 

#researcher pages
@login_required(login_url='/login/')
def researcher(request):
    context = {}
    parasite = request.GET.get('parasite')
    posts = Post.objects.filter(post_type='0').order_by('-date_posted')
    if parasite != None:
        posts = posts.filter(
            parasite__name=parasite)
    parasites = Parasite.objects.all()
    context['parasites'] = parasites
    context['posts'] = posts
    return render(request,'parasites_app/researcher.html', context)

@login_required(login_url='/login/')
def researcher_post(request, pk):
    post = Post.objects.filter(pk = pk)[0]
    comments = Comment.objects.filter(post=post)
    files = File.objects.filter(post=post)
    context_dict={}
    context_dict['post'] = post
    context_dict['profile'] = post.user
    context_dict['comments'] = comments
    context_dict['comment_form'] = CommentForm()
    context_dict['files'] = files
    if request.user.is_authenticated:
        if request.method == 'POST':
            if 'Comment' in request.POST:
                comment_form = CommentForm(request.POST)
                if comment_form.is_valid():
                    comment = comment_form.save(commit=False)
                    if request.user.is_superuser:
                        comment.user = request.user
                    else:
                        comment.user = request.user
                    comment.post = context_dict['post']
                    comment.save()
                return redirect(reverse('researcher_post', kwargs={'pk':pk}))
 
    return render(request,'parasites_app/researcher_post.html',context = context_dict)


#clinician pages
@clinician_required(login_url='/login/')
def clinician_post(request, pk):
    post = Post.objects.filter(pk = pk)[0]
    comments = Comment.objects.filter(post=post)
    files = File.objects.filter(post=post)
    context_dict={}
    context_dict['post'] = post
    context_dict['profile'] = post.user
    context_dict['comments'] = comments
    context_dict['comment_form'] = CommentForm()
    context_dict['files'] = files
    if request.user.is_authenticated:
        if request.method == 'POST':
            if 'Comment' in request.POST:
                comment_form = CommentForm(request.POST)
                if comment_form.is_valid():
                    comment = comment_form.save(commit=False)
                    if request.user.is_superuser:
                        comment.user = request.user
                    else:
                        comment.user = request.user
                    comment.post = context_dict['post']
                    comment.save()
                return redirect(reverse('clinician_post', kwargs={'pk':pk}))
    return render(request,'parasites_app/clinician_post.html',context = context_dict)

#Clinican page
@login_required(login_url='/login/')
@clinician_required
def clinician(request):
    context = {}
    parasite = request.GET.get('parasite')
    posts = Post.objects.filter(post_type='1').order_by('-date_posted')
    if parasite != None:
        posts = posts.filter(
            parasite__name=parasite)
    parasites = Parasite.objects.all()
    context['parasites'] = parasites
    context['posts'] = posts
    return render(request,'parasites_app/clinician.html', context)

#add either clinician or researcher post (must be last)
@login_required(login_url='/login/')
def add_researcher_post(request):
    context = {}
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        context['post_form'] = post_form
        if request.user.is_authenticated and post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.parasite = get_object_or_404(Parasite, pk=request.POST.get('parasite'))
            post.post_type = '0'
            post.save()
            count = 1

Parasites Web Application/cs36-main-master/templates/parasites_app/clinician_post.html
{% extends "parasites_app/base.html"  %}
{% load static %}

{% block content_block %}    
<br>



    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Clinician.css' %}" xmlns="http://www.w3.org/1999/html"/>


<!-- the post -->
{% if post.post_type != '1' %}
<div class="container">
    <div class="row">  
        <div class="card" id="post_info">
            <div class="card-body">
                This page does not exist. Please return to the 
                <a href="{% url 'home' %}">home</a> page.
                

            </div>
        </div>
    </div>
 </div>

{% else %}
<div class="container">

    <div class="row">  
        <div class="card" id="post_info">
            <div class="card-body">
                        <h4>{{post.title}} </h4>
                        <br>
                        <img id="uploader_pp" src={{ profile.picture.url }}>
                        <strong> {{ profile.email }}</strong>&emsp;
                        {{ post.date_posted }} &emsp;
                    <strong>Parasite: </strong> <a href="{% url 'view_parasite' post.parasite.slug %}">{{post.parasite.name}}</a><br>&emsp;

                    
                     <br>
                   
                    <p class="text-center">
                    {% if files %}
                        {% for file in files %}
                        <br>
                        <br>
                            {% if file.file_type == '0' %}
                                <video width="600" height="400"  autoplay="autoplay" controls="controls" preload="preload">
            						<source style="width: 30pk; height: 30pk;" src="{{ file.file.url }}" type="video/mp4"></source>
            					</video>
            					
                            {% endif %}
                            <br>
                            <br>
                            {% if file.file_type == '1' %}
                                <img style="width: 30%; height: 30%;" src="{{file.file.url}}">
                            {% endif %}
                        {% endfor %}
                        
                        <br>
                        {% for file in files %}
                            <a href="{{file.file.url}}"}}" download>File {{file.number}} ({{file.get_file_type_display}})</a></h1>
                        {% endfor %}
                        
                       
                     {% endif %}

                     
                    
                     
                      
                             
                            <div class="text1">
                                {{ post.text |safe}}
                            
                            </div>

                    </p>
                     
                   
                    
                   

            </div>
        </div>
    </div>


</div>





<!-- End of the post -->

<!-- Comment section -->
<div class="container">
    <div class="row">  
        <div class="card" id="profile_description">
            <div class="card-body">
                {% if comments %}
                <h4>Comments: </h4> <br>
                {% for c in comments %}
                <div class="comment">
                    <img class="comment_pp" src={{ c.user.picture.url }}>
                    <strong>{{ c.user.email }}</strong> &emsp;{{c.date}}
                    <div class="comment_text">
                        {{ c.text }}
                    </div>
                    <br>
                </div>
                {% endfor %}
            
                {% else %}
                <h4>No comments yet...</h4>
                {% endif %}
                <br>
            </div>
                    <!-- if the user is logged in, the user can comment -->
                    {% if user.is_authenticated %}
                    <div class="form-group">
                        <form  id="comment_form" method="post" action="{% url 'clinician_post' post.pk %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            <input type="submit" name="Comment" value="Comment" />
                        </form>
                    </div>

                    {% else %}
                        <input class="form-control" type="text" placeholder="Log in to comment..." readonly>
                    {% endif %}
                                                <br/>

        </div>
    </div>
</div>
<br>
        <!-- End of Comment section -->
{% endif %}      

{% endblock %}

Parasites Web Application/cs36-main-master/templates/parasites_app/post.html
{% extends 'parasites_app/base.html' %}
{% load static %}

{% block style_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title_block %}

{% endblock %}

{% block body_block %}
	{% if post %}
	<div class="bg-secondary rounded" style="margin:auto; width:50%; border:3px; padding: 25px; padding-right:5px; margin-top:40px; margin-bottom: 50px; box-shadow: 5px 10px;">
	<h1>{{ post.title |safe}}:</h1>
	<br></br>
	<p>{{ post.text |safe}}</p>
		
	<!-- need to implement comments -->
		
	{% else %}
		<strong>No post accessible.</strong>
	{% endif %}
	</div>
	
{% endblock %}

{% block footer %}

{% endblock %}

Parasites Web Application/cs36-main-master/templates/parasites_app/public_post.html
{% extends "parasites_app/base.html"  %}
{% load static %}

{% block content_block %}    
<br>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible" content="IE-edge'>
    <title>Post</title>
    <meta name='viewport' content='width-device-width, initial-scale=1'>

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Home_Post.css' %}" xmlns="http://www.w3.org/1999/html"/>
</head>

<!-- the post -->
{% if post.post_type != '2' %}
<div class="container">
    <div class="row">  
        <div class="card" id="post_info">
            <div class="card-body">
                This page does not exist. Please return to the 
                <a href="{% url 'home' %}">home</a> page.
                

                </div>
            </div>
            <br>
{% else %}
<div class="container">
    <div class="row">  
        <div class="card" id="post_info">
            <div class="card-body">
                <h4>{{post.title}} </h4>
                <img id="uploader_pp" src={{ profile.picture.url }}>
                        <strong> {{ profile.email }}</strong>&emsp;
                        {{ post.date_posted }} &emsp;
                    <strong>Parasite: </strong><a href="{% url 'view_parasite' post.parasite.slug %}">{{post.parasite.name}} </a> <br>&emsp;

                    
                     <p class="aligncenter">
                    {% if files %}
                        {% for file in files %}
                            {% if file.file_type == '0' %}
                                <video width="600" height="400" autoplay="autoplay" controls="controls" preload="preload">
            						<source style="width: 30pk; height: 30pk;" src="{{ file.file.url }}" type="video/mp4"></source>
            					</video>
            					</br>
                            {% endif %}
                            {% if file.file_type == '1' %}
                                <img style="width: 30%; height: 30%;" src="{{file.file.url}}">
                            {% endif %}
                        {% endfor %}
                        {% for file in files %}
                            <a href="{{file.file.url}}"}}" download>File {{file.number}} ({{file.get_file_type_display}})</a></h1>
                        {% endfor %}
                     {% endif %}
                      </p>

                    {{ post.text }}
                            <br/><br/>


                </div>
            </div>
            <br>
{% endif %}
<!-- End of the post -->

        </div>
    </div>
</div>
{% endblock %}

Parasites Web Application/cs36-main-master/templates/parasites_app/researcher_post.html
{% extends "parasites_app/base.html"  %}
{% load static %}

{% block content_block %}    
<br>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible" content="IE-edge'>
    <title>Post</title>
    <meta name='viewport' content='width-device-width, initial-scale=1'>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Clinician.css' %}" xmlns="http://www.w3.org/1999/html"/>
</head>

<!-- the post -->
{% if post.post_type != '0' %}
<div class="container">
    <div class="row">  
        <div class="card" id="post_info">
            <div class="card-body">
                This page does not exist. Please return to the 
                <a href="{% url 'home' %}">home</a> page.
                

                </div>
            </div>
            <br>
{% else %}
<div class="container">
    <div class="row">  
            <div class="card" id="post_info">
                <div class="card-body">
                        <h4>{{post.title|safe}} </h4>
                        <br>
                        <img id="uploader_pp" src={{ profile.picture.url }}>
                        <strong> {{ profile.email }}</strong>&emsp;
                        {{ post.date_posted }} &emsp;
                    <strong>Parasite: </strong> <a href="{% url 'view_parasite' post.parasite.slug %}">{{post.parasite.name}} </a><br>&emsp;

                    
                     
                    <p class="text-center">
                        {% if files %}
                        {% for file in files %}
                        <br>
                        <br>
                            {% if file.file_type == '0' %}
                                <video width="600" height="400" controls="controls" >
            						<source style="width: 30pk; height: 30pk;" src="{{ file.file.url }}" type="video/mp4"></source>
            					</video>
            					</br>
                            {% endif %}
                            <br>
                            <br>
                            {% if file.file_type == '1' %}
                                <img style="width: 30%; height: 30%;" src="{{file.file.url}}">
                               
                            {% endif %}
                        {% endfor %}
                        <br>
                        <br>
                        {% for file in files %}
                            <a href="{{file.file.url}}"}}" download>File {{file.number}} ({{file.get_file_type_display}})</a></h1>
                        {% endfor %}
                        {% endif %}
                      </p>
                      
                      <div class="container3">
                        <div class="container2">
                            {% if post.file %}
                        <img style="width: 30%;height: 30%;" src="{{post.file.url}}">
                        {% endif %}
                      
                        </div>
                         
                        <div class="text1">
                            {{ post.text |safe}}
                        
                        </div>

                    </div>
               


                </div>
            </div>
            <br>
<!-- End of the post -->

<!-- Comment section -->
<div class="container">
    <div class="row">  
        <div class="card" id="profile_description">
            <div class="card-body">
                {% if comments %}
                <h4>Comments: </h4> <br>
                {% for c in comments %}
                <div class="comment">
                    <img class="comment_pp" src={{ c.user.picture.url }}>
                    <strong>{{ c.user.email }}</strong> &emsp;{{c.date}}
                    <div class="comment_text">
                        {{ c.text |safe}}
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <h4>No comments yet...</h4>
                {% endif %}
            </div>
                    <!-- if the user is logged in, the user can comment -->
                    {% if user.is_authenticated %}
                    <div class="form-group">
                        <form  id="comment_form" method="post" action="{% url 'researcher_post' post.pk %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            <input type="submit" name="Comment" value="Comment" />
                        </form>
                    </div>

                    {% else %}
                        <input class="form-control" type="text" placeholder="Log in to comment..." readonly>
                    {% endif %}
                            <br/>

                </div>
            </div>
        </div>
        <!-- End of Comment section -->

        </div>
    </div>
</div>
{% endif %}        

{% endblock %}